# Hangman Game using pygame

# -----------------------------------------------------------------------------------

import pygame
import random
import math

# -----------------------------------------------------------------------------------

# Basic operations:

pygame.init()  # initializing the pygame
WIDTH = 1000
HEIGHT = 650
window = pygame.display.set_mode((WIDTH, HEIGHT))  # geometry of pygame
pygame.display.set_caption('HANGMAN')  # sets the caption at the top left
fps = 60  # how smooth the gameplay is
clock = pygame.time.Clock()
run = True

# -----------------------------------------------------------------------------------

# images

images = []
img0 = pygame.image.load(r'D:\Python\School_project\Project 1 (game)\Hangman_images\hangman0.png')
img1 = pygame.image.load(r'D:\Python\School_project\Project 1 (game)\Hangman_images\hangman1.png')
img2 = pygame.image.load(r'D:\Python\School_project\Project 1 (game)\Hangman_images\hangman2.png')
img3 = pygame.image.load(r'D:\Python\School_project\Project 1 (game)\Hangman_images\hangman3.png')
img4 = pygame.image.load(r'D:\Python\School_project\Project 1 (game)\Hangman_images\hangman4.png')
img5 = pygame.image.load(r'D:\Python\School_project\Project 1 (game)\Hangman_images\hangman5.png')
img6 = pygame.image.load(r'D:\Python\School_project\Project 1 (game)\Hangman_images\hangman6.png')
images.append(img0)
images.append(img1)
images.append(img2)
images.append(img3)
images.append(img4)
images.append(img5)
images.append(img6)
print(images)

# -----------------------------------------------------------------------------------

# Fonts

font1 = pygame.font.SysFont('Menlo', size=40)  # for the letters
font2 = pygame.font.SysFont('Menlo', size=60)  # for the words
font3 = pygame.font.SysFont('Menlo', size=70)  # for the top title

# -----------------------------------------------------------------------------------

# button Variables - For the alphaets

radius = 20  # radius of sphere inside which alphabet is ( -- )
gap = 15  # the gap between 2 circles  | --- ( ) --- () -- |
letters = []

# ---------------------------------------------------------------------

# from which position should we start placing the letters with suitable gaps
start_x = round((WIDTH - (radius * 2 + gap) * 13) / 2)  # formula to give spacing between letters
start_y = 400  # this one doesnt matter as much as x co-ordinate
A = 65  # this is the ASCII value from which we'll draw the letter
for i in range(26):
    x = start_x + gap * 2 + ((radius * 2 + gap) * (i % 13))  # i%13 is done for 2 rows
    y = start_y + ((i // 13)) * (gap + radius * 2)
    letters.append([x, y, chr(A + i), True])  # in the position x, y append the alphabets
    
# ----------------------------------------------------------------------


# -----------------------------------------------------------------------------------

# Game Variables  ---- when we start the game we should tell which image should load first and all

hangman_initial_status = 0  # what image that i want to draw at each point of the game , so that's why start with surface
words = [
    'PEOPLE',
    'HISTORY',
    'WAY',
    'ART',
    'WORLD',
    'INFORMATION',
    'MAP',
    'TWO',
    'FAMILY',
    'GOVERNMENT' ,
    'HEALTH' ,
    'SYSTEM' ,
    'COMPUTER' ,
    'MEAT' ,
    'YEAR' ,
    'THANKS' ,
    'MUSIC' ,
    'PERSON' ,
    'READING' ,
    'METHOD' ,
    'DATA' ,
    'FOOD' ,
    'UNDERSTANDING' ,
    'THEORY' ,
    'LAW' ,
    'BIRD' ,
    'LITERATURE' ,
    'PROBLEM' ,
    'SOFTWARE' ,
    'CONTROL' ,
    'KNOWLEDGE' ,
    'POWER' ,
    'ABILITY' ,
    'ECONOMICS' ,
    'LOVE' ,
    'INTERNET' ,
    'TELEVISION' ,
    'SCIENCE' ,
    'LIBRARY' ,
    'NATURE' ,
    'FACT' ,
    'PRODUCT' ,
    'IDEA' ,
    'TEMPERATURE' ,
    'INVESTMENT' ,
    'AREA' ,
    'SOCIETY' ,
    'ACTIVITY' ,
    'STORY' ,
    'INDUSTRY' ,
    'MEDIA' ,
    'THING' ,
    'OVEN' ,
    'COMMUNITY' ,
    'DEFINITION' ,
    'SAFETY' ,
    'QUALITY' ,
    'DEVELOPMENT' ,
    'LANGUAGE' ,
    'MANAGEMENT' ,
    'PLAYER' ,
    'VARIETY' ,
    'VIDEO' ,
    'WEEK' ,
    'SECURITY' ,
    'COUNTRY' ,
    'EXAM' ,
    'MOVIE' ,
    'ORGANIZATION' ,
    'EQUIPMENT' ,
    'PHYSICS' ,
    'ANALYSIS' ,
    'POLICY' ,
    'SERIES' ,
    'THOUGHT' ,
    'BASIS' ,
    'BOYFRIEND' ,
    'DIRECTION' ,
    'STRATEGY' ,
    'TECHNOLOGY' ,
    'ARMY' ,
    'CAMERA' ,
    'FREEDOM' ,
    'PAPER' ,
    'ENVIRONMENT' ,
    'CHILD' ,
    'INSTANCE' ,
    'MONTH' ,
    'TRUTH' ,
    'MARKETING' ,
    'UNIVERSITY' ,
    'WRITING' ,
    'ARTICLE' ,
    'DEPARTMENT' ,
    'DIFFERENCE' ,
    'GOAL' ,
    'NEWS' ,
    'AUDIENCE' ,
    'FISHING' ,
    'GROWTH' ,
    'INCOME' ,
    'MARRIAGE' ,
    'USER' ,
    'COMBINATION' ,
    'FAILURE' ,
    'MEANING' ,
    'MEDICINE' ,
    'PHILOSOPHY' ,
    'TEACHER' ,
    'COMMUNICATION' ,
    'NIGHT' ,
    'CHEMISTRY' ,
    'DISEASE' ,
    'DISK' ,
    'ENERGY' ,
    'NATION' ,
    'ROAD' ,
    'ROLE' ,
    'SOUP' ,
    'ADVERTISING' ,
    'LOCATION' ,
    'SUCCESS' ,
    'ADDITION' ,
    'APARTMENT' ,
    'EDUCATION' ,
    'MATH' ,
    'MOMENT' ,
    'PAINTING' ,
    'POLITICS' ,
    'ATTENTION' ,
    'DECISION' ,
    'EVENT' ,
    'PROPERTY' ,
    'SHOPPING' ,
    'STUDENT' ,
    'WOOD' ,
    'COMPETITION' ,
    'DISTRIBUTION' ,
    'ENTERTAINMENT' ,
    'OFFICE' ,
    'POPULATION' ,
    'PRESIDENT' ,
    'UNIT' ,
    'CATEGORY' ,
    'CIGARETTE' ,
    'CONTEXT' ,
    'INTRODUCTION' ,
    'OPPORTUNITY' ,
    'PERFORMANCE' ,
    'DRIVER' ,
    'FLIGHT' ,
    'LENGTH' ,
    'MAGAZINE' ,
    'NEWSPAPER' ,
    'RELATIONSHIP' ,
    'TEACHING' ,
    'CELL' ,
    'DEALER' ,
    'DEBATE' ,
    'FINDING' ,
    'LAKE' ,
    'MEMBER' ,
    'MESSAGE' ,
    'PHONE' ,
    'SCENE' ,
    'APPEARANCE' ,
    'ASSOCIATION' ,
    'CONCEPT' ,
    'CUSTOMER' ,
    'DEATH' ,
    'DISCUSSION' ,
    'HOUSING' ,
    'INFLATION' ,
    'INSURANCE' ,
    'MOOD' ,
    'WOMAN' ,
    'ADVICE' ,
    'BLOOD' ,
    'EFFORT' ,
    'EXPRESSION' ,
    'IMPORTANCE' ,
    'OPINION' ,
    'PAYMENT' ,
    'REALITY' ,
    'RESPONSIBILITY' ,
    'SITUATION' ,
    'SKILL' ,
    'STATEMENT' ,
    'WEALTH' ,
    'APPLICATION' ,
    'CITY' ,
    'COUNTY' ,
    'DEPTH' ,
    'ESTATE' ,
    'FOUNDATION' ,
    'GRANDMOTHER' ,
    'HEART' ,
    'PERSPECTIVE' ,
    'PHOTO' ,
    'RECIPE' ,
    'STUDIO' ,
    'TOPIC' ,
    'COLLECTION' ,
    'DEPRESSION' ,
    'IMAGINATION' ,
    'PASSION' ,
    'PERCENTAGE' ,
    'RESOURCE' ,
    'SETTING' ,
    'AD' ,
    'AGENCY' ,
    'COLLEGE' ,
    'CONNECTION' ,
    'CRITICISM' ,
    'DEBT' ,
    'DESCRIPTION' ,
    'MEMORY' ,
    'PATIENCE' ,
    'SECRETARY' ,
    'SOLUTION' ,
    'ADMINISTRATION' ,
    'ASPECT' ,
    'ATTITUDE' ,
    'DIRECTOR' ,
    'PERSONALITY' ,
    'PSYCHOLOGY' ,
    'RECOMMENDATION' ,
    'RESPONSE' ,
    'SELECTION' ,
    'STORAGE' ,
    'VERSION' ,
    'ALCOHOL' ,
    'ARGUMENT' ,
    'COMPLAINT' ,
    'CONTRACT' ,
    'EMPHASIS' ,
    'HIGHWAY' ,
    'LOSS' ,
    'MEMBERSHIP' ,
    'POSSESSION' ,
    'PREPARATION' ,
    'STEAK' ,
    'UNION' ,
    'AGREEMENT' ,
    'CANCER' ,
    'CURRENCY' ,
    'EMPLOYMENT' ,
    'ENGINEERING' ,
    'ENTRY' ,
    'INTERACTION' ,
    'LIMIT' ,
    'MIXTURE' ,
    'PREFERENCE' ,
    'REGION' ,
    'REPUBLIC' ,
    'SEAT' ,
    'TRADITION' ,
    'VIRUS' ,
    'ACTOR' ,
    'CLASSROOM' ,
    'DELIVERY' ,
    'DEVICE' ,
    'DIFFICULTY' ,
    'DRAMA' ,
    'ELECTION' ,
    'ENGINE' ,
    'FOOTBALL' ,
    'GUIDANCE' ,
    'HOTEL' ,
    'MATCH' ,
    'OWNER' ,
    'PRIORITY' ,
    'PROTECTION' ,
    'SUGGESTION' ,
    'TENSION' ,
    'VARIATION' ,
    'ANXIETY' ,
    'ATMOSPHERE' ,
    'AWARENESS' ,
    'BREAD' ,
    'CLIMATE' ,
    'COMPARISON' ,
    'CONFUSION' ,
    'CONSTRUCTION' ,
    'ELEVATOR' ,
    'EMOTION' ,
    'EMPLOYEE' ,
    'EMPLOYER' ,
    'GUEST' ,
    'HEIGHT' ,
    'LEADERSHIP' ,
    'MALL' ,
    'MANAGER' ,
    'OPERATION' ,
    'RECORDING' ,
    'RESPECT' ,
    'SAMPLE' ,
    'TRANSPORTATION' ,
    'BORING' ,
    'CHARITY' ,
    'COUSIN' ,
    'DISASTER' ,
    'EDITOR' ,
    'EFFICIENCY' ,
    'EXCITEMENT' ,
    'EXTENT' ,
    'FEEDBACK' ,
    'GUITAR' ,
    'HOMEWORK' ,
    'LEADER' ,
    'MOM' ,
    'OUTCOME' ,
    'PERMISSION' ,
    'PRESENTATION' ,
    'PROMOTION' ,
    'REFLECTION' ,
    'REFRIGERATOR' ,
    'RESOLUTION' ,
    'REVENUE' ,
    'SESSION' ,
    'SINGER' ,
    'TENNIS' ,
    'BASKET' ,
    'BONUS' ,
    'CABINET' ,
    'CHILDHOOD' ,
    'CHURCH' ,
    'CLOTHES' ,
    'COFFEE' ,
    'DINNER' ,
    'DRAWING' ,
    'HAIR' ,
    'HEARING' ,
    'INITIATIVE' ,
    'JUDGMENT' ,
    'LAB' ,
    'MEASUREMENT' ,
    'MODE' ,
    'MUD' ,
    'ORANGE' ,
    'POETRY' ,
    'POLICE' ,
    'POSSIBILITY' ,
    'PROCEDURE' ,
    'QUEEN' ,
    'RATIO' ,
    'RELATION' ,
    'RESTAURANT' ,
    'SATISFACTION' ,
    'SECTOR' ,
    'SIGNATURE' ,
    'SIGNIFICANCE' ,
    'SONG' ,
    'TOOTH' ,
    'TOWN' ,
    'VEHICLE' ,
    'VOLUME' ,
    'WIFE' ,
    'ACCIDENT' ,
    'AIRPORT' ,
    'APPOINTMENT' ,
    'ARRIVAL' ,
    'ASSUMPTION' ,
    'BASEBALL' ,
    'CHAPTER' ,
    'COMMITTEE' ,
    'CONVERSATION' ,
    'DATABASE' ,
    'ENTHUSIASM' ,
    'ERROR' ,
    'EXPLANATION' ,
    'FARMER' ,
    'GATE' ,
    'GIRL' ,
    'HALL' ,
    'HISTORIAN' ,
    'HOSPITAL' ,
    'INJURY' ,
    'INSTRUCTION' ,
    'MAINTENANCE' ,
    'MANUFACTURER' ,
    'MEAL' ,
    'PERCEPTION' ,
    'PIE' ,
    'POEM' ,
    'PRESENCE' ,
    'PROPOSAL' ,
    'RECEPTION' ,
    'REPLACEMENT' ,
    'REVOLUTION' ,
    'RIVER' ,
    'SON' ,
    'SPEECH' ,
    'TEA' ,
    'VILLAGE' ,
    'WARNING' ,
    'WINNER' ,
    'WORKER' ,
    'WRITER' ,
    'ASSISTANCE' ,
    'BREATH' ,
    'BUYER' ,
    'CHEST' ,
    'CHOCOLATE' ,
    'CONCLUSION' ,
    'CONTRIBUTION' ,
    'COOKIE' ,
    'COURAGE' ,
    'DAD' ,
    'DESK' ,
    'DRAWER' ,
    'ESTABLISHMENT' ,
    'EXAMINATION' ,
    'GARBAGE' ,
    'GROCERY' ,
    'HONEY' ,
    'IMPRESSION' ,
    'IMPROVEMENT' ,
    'INDEPENDENCE' ,
    'INSECT' ,
    'INSPECTION' ,
    'INSPECTOR' ,
    'KING' ,
    'LADDER' ,
    'MENU' ,
    'PENALTY' ,
    'PIANO' ,
    'POTATO' ,
    'PROFESSION' ,
    'PROFESSOR' ,
    'QUANTITY' ,
    'REACTION' ,
    'REQUIREMENT' ,
    'SALAD' ,
    'SISTER' ,
    'SUPERMARKET' ,
    'TONGUE' ,
    'WEAKNESS' ,
    'WEDDING' ,
    'AFFAIR' ,
    'AMBITION' ,
    'ANALYST' ,
    'APPLE' ,
    'ASSIGNMENT' ,
    'ASSISTANT' ,
    'BATHROOM' ,
    'BEDROOM' ,
    'BEER' ,
    'BIRTHDAY' ,
    'CELEBRATION' ,
    'CHAMPIONSHIP' ,
    'CHEEK' ,
    'CLIENT' ,
    'CONSEQUENCE' ,
    'DEPARTURE' ,
    'DIAMOND' ,
    'DIRT' ,
    'EAR' ,
    'FORTUNE' ,
    'FRIENDSHIP' ,
    'FUNERAL' ,
    'GENE' ,
    'GIRLFRIEND' ,
    'HAT' ,
    'INDICATION' ,
    'INTENTION' ,
    'LADY' ,
    'MIDNIGHT' ,
    'NEGOTIATION' ,
    'OBLIGATION' ,
    'PASSENGER' ,
    'PIZZA' ,
    'PLATFORM' ,
    'POET' ,
    'POLLUTION' ,
    'RECOGNITION' ,
    'REPUTATION' ,
    'SHIRT' ,
    'SIR' ,
    'SPEAKER' ,
    'STRANGER' ,
    'SURGERY' ,
    'SYMPATHY' ,
    'TALE' ,
    'THROAT' ,
    'TRAINER' ,
    'UNCLE' ,
    'YOUTH' ,
    'TIME' ,
    'WORK' ,
    'FILM' ,
    'WATER' ,
    'MONEY' ,
    'EXAMPLE' ,
    'WHILE' ,
    'BUSINESS' ,
    'STUDY' ,
    'GAME' ,
    'LIFE' ,
    'FORM' ,
    'AIR' ,
    'DAY' ,
    'PLACE' ,
    'NUMBER' ,
    'PART' ,
    'FIELD' ,
    'FISH' ,
    'BACK' ,
    'PROCESS' ,
    'HEAT' ,
    'HAND' ,
    'EXPERIENCE' ,
    'JOB' ,
    'BOOK' ,
    'END' ,
    'POINT' ,
    'TYPE' ,
    'HOME' ,
    'ECONOMY' ,
    'VALUE' ,
    'BODY' ,
    'MARKET' ,
    'GUIDE' ,
    'INTEREST' ,
    'STATE' ,
    'RADIO' ,
    'COURSE' ,
    'COMPANY' ,
    'PRICE' ,
    'SIZE' ,
    'CARD' ,
    'LIST' ,
    'MIND' ,
    'TRADE' ,
    'LINE' ,
    'CARE' ,
    'GROUP' ,
    'RISK' ,
    'WORD' ,
    'FAT' ,
    'FORCE' ,
    'KEY' ,
    'LIGHT' ,
    'TRAINING' ,
    'NAME' ,
    'SCHOOL' ,
    'TOP' ,
    'AMOUNT' ,
    'LEVEL' ,
    'ORDER' ,
    'PRACTICE' ,
    'RESEARCH' ,
    'SENSE' ,
    'SERVICE' ,
    'PIECE' ,
    'WEB' ,
    'BOSS' ,
    'SPORT' ,
    'FUN' ,
    'HOUSE' ,
    'PAGE' ,
    'TERM' ,
    'TEST' ,
    'ANSWER' ,
    'SOUND' ,
    'FOCUS' ,
    'MATTER' ,
    'KIND' ,
    'SOIL' ,
    'BOARD' ,
    'OIL' ,
    'PICTURE' ,
    'ACCESS' ,
    'GARDEN' ,
    'RANGE' ,
    'RATE' ,
    'REASON' ,
    'FUTURE' ,
    'SITE' ,
    'DEMAND' ,
    'EXERCISE' ,
    'IMAGE' ,
    'CASE' ,
    'CAUSE' ,
    'COAST' ,
    'ACTION' ,
    'AGE' ,
    'BAD' ,
    'BOAT' ,
    'RECORD' ,
    'RESULT' ,
    'SECTION' ,
    'BUILDING' ,
    'MOUSE' ,
    'CASH' ,
    'CLASS' ,
    'NOTHING' ,
    'PERIOD' ,
    'PLAN' ,
    'STORE' ,
    'TAX' ,
    'SIDE' ,
    'SUBJECT' ,
    'SPACE' ,
    'RULE' ,
    'STOCK' ,
    'WEATHER' ,
    'CHANCE' ,
    'FIGURE' ,
    'MAN' ,
    'MODEL' ,
    'SOURCE' ,
    'BEGINNING' ,
    'EARTH' ,
    'PROGRAM' ,
    'CHICKEN' ,
    'DESIGN' ,
    'FEATURE' ,
    'HEAD' ,
    'MATERIAL' ,
    'PURPOSE' ,
    'QUESTION' ,
    'ROCK' ,
    'SALT' ,
    'ACT' ,
    'BIRTH' ,
    'CAR' ,
    'DOG' ,
    'OBJECT' ,
    'SCALE' ,
    'SUN' ,
    'NOTE' ,
    'PROFIT' ,
    'RENT' ,
    'SPEED' ,
    'STYLE' ,
    'WAR' ,
    'BANK' ,
    'CRAFT' ,
    'HALF' ,
    'INSIDE' ,
    'OUTSIDE' ,
    'STANDARD' ,
    'BUS' ,
    'EXCHANGE' ,
    'EYE' ,
    'FIRE' ,
    'POSITION' ,
    'PRESSURE' ,
    'STRESS' ,
    'ADVANTAGE' ,
    'BENEFIT' ,
    'BOX' ,
    'FRAME' ,
    'ISSUE' ,
    'STEP' ,
    'CYCLE' ,
    'FACE' ,
    'ITEM' ,
    'METAL' ,
    'PAINT' ,
    'REVIEW' ,
    'ROOM' ,
    'SCREEN' ,
    'STRUCTURE' ,
    'VIEW' ,
    'ACCOUNT' ,
    'BALL' ,
    'DISCIPLINE' ,
    'MEDIUM' ,
    'SHARE' ,
    'BALANCE' ,
    'BIT' ,
    'BLACK' ,
    'BOTTOM' ,
    'CHOICE' ,
    'GIFT' ,
    'IMPACT' ,
    'MACHINE' ,
    'SHAPE' ,
    'TOOL' ,
    'WIND' ,
    'ADDRESS' ,
    'AVERAGE' ,
    'CAREER' ,
    'CULTURE' ,
    'MORNING' ,
    'POT' ,
    'SIGN' ,
    'TABLE' ,
    'TASK' ,
    'CONDITION' ,
    'CONTACT' ,
    'CREDIT' ,
    'EGG' ,
    'HOPE' ,
    'ICE' ,
    'NETWORK' ,
    'NORTH' ,
    'SQUARE' ,
    'ATTEMPT' ,
    'DATE' ,
    'EFFECT' ,
    'LINK' ,
    'POST' ,
    'STAR' ,
    'VOICE' ,
    'CAPITAL' ,
    'CHALLENGE' ,
    'FRIEND' ,
    'SELF' ,
    'SHOT' ,
    'BRUSH' ,
    'COUPLE' ,
    'EXIT' ,
    'FRONT' ,
    'FUNCTION' ,
    'LACK' ,
    'LIVING' ,
    'PLANT' ,
    'PLASTIC' ,
    'SPOT' ,
    'SUMMER' ,
    'TASTE' ,
    'THEME' ,
    'TRACK' ,
    'WING' ,
    'BRAIN' ,
    'BUTTON' ,
    'CLICK' ,
    'DESIRE' ,
    'FOOT' ,
    'GAS' ,
    'INFLUENCE' ,
    'NOTICE' ,
    'RAIN' ,
    'WALL' ,
    'BASE' ,
    'DAMAGE' ,
    'DISTANCE' ,
    'FEELING' ,
    'PAIR' ,
    'SAVINGS' ,
    'STAFF' ,
    'SUGAR' ,
    'TARGET' ,
    'TEXT' ,
    'ANIMAL' ,
    'AUTHOR' ,
    'BUDGET' ,
    'DISCOUNT' ,
    'FILE' ,
    'GROUND' ,
    'LESSON' ,
    'MINUTE' ,
    'OFFICER' ,
    'PHASE' ,
    'REFERENCE' ,
    'REGISTER' ,
    'SKY' ,
    'STAGE' ,
    'STICK' ,
    'TITLE' ,
    'TROUBLE' ,
    'BOWL' ,
    'BRIDGE' ,
    'CAMPAIGN' ,
    'CHARACTER' ,
    'CLUB' ,
    'EDGE' ,
    'EVIDENCE' ,
    'FAN' ,
    'LETTER' ,
    'LOCK' ,
    'MAXIMUM' ,
    'NOVEL' ,
    'OPTION' ,
    'PACK' ,
    'PARK' ,
    'PLENTY' ,
    'QUARTER' ,
    'SKIN' ,
    'SORT' ,
    'WEIGHT' ,
    'BABY' ,
    'BACKGROUND' ,
    'CARRY' ,
    'DISH' ,
    'FACTOR' ,
    'FRUIT' ,
    'GLASS' ,
    'JOINT' ,
    'MASTER' ,
    'MUSCLE' ,
    'RED' ,
    'STRENGTH' ,
    'TRAFFIC' ,
    'TRIP' ,
    'VEGETABLE' ,
    'APPEAL' ,
    'CHART' ,
    'GEAR' ,
    'IDEAL' ,
    'KITCHEN' ,
    'LAND' ,
    'LOG' ,
    'MOTHER' ,
    'NET' ,
    'PARTY' ,
    'PRINCIPLE' ,
    'RELATIVE' ,
    'SALE' ,
    'SEASON' ,
    'SIGNAL' ,
    'SPIRIT' ,
    'STREET' ,
    'TREE' ,
    'WAVE' ,
    'BELT' ,
    'BENCH' ,
    'COMMISSION' ,
    'COPY' ,
    'DROP' ,
    'MINIMUM' ,
    'PATH' ,
    'PROGRESS' ,
    'PROJECT' ,
    'SEA' ,
    'SOUTH' ,
    'STATUS' ,
    'STUFF' ,
    'TICKET' ,
    'TOUR' ,
    'ANGLE' ,
    'BLUE' ,
    'BREAKFAST' ,
    'CONFIDENCE' ,
    'DAUGHTER' ,
    'DEGREE' ,
    'DOCTOR' ,
    'DOT' ,
    'DREAM' ,
    'DUTY' ,
    'ESSAY' ,
    'FATHER' ,
    'FEE' ,
    'FINANCE' ,
    'HOUR' ,
    'JUICE' ,
    'LUCK' ,
    'MILK' ,
    'MOUTH' ,
    'PEACE' ,
    'PIPE' ,
    'STABLE' ,
    'STORM' ,
    'SUBSTANCE' ,
    'TEAM' ,
    'TRICK' ,
    'AFTERNOON' ,
    'BAT' ,
    'BEACH' ,
    'BLANK' ,
    'CATCH' ,
    'CHAIN' ,
    'CONSIDERATION' ,
    'CREAM' ,
    'CREW' ,
    'DETAIL' ,
    'GOLD' ,
    'INTERVIEW' ,
    'KID' ,
    'MARK' ,
    'MISSION' ,
    'PAIN' ,
    'PLEASURE' ,
    'SCORE' ,
    'SCREW' ,
    'SHOP' ,
    'SHOWER' ,
    'SUIT' ,
    'TONE' ,
    'WINDOW' ,
    'AGENT' ,
    'BAND' ,
    'BATH' ,
    'BLOCK' ,
    'BONE' ,
    'CALENDAR' ,
    'CANDIDATE' ,
    'CAP' ,
    'COAT' ,
    'CONTEST' ,
    'CORNER' ,
    'COURT' ,
    'CUP' ,
    'DISTRICT' ,
    'DOOR' ,
    'EAST' ,
    'FINGER' ,
    'GARAGE' ,
    'GUARANTEE' ,
    'HOLE' ,
    'HOOK' ,
    'IMPLEMENT' ,
    'LAYER' ,
    'LECTURE' ,
    'LIE' ,
    'MANNER' ,
    'MEETING' ,
    'NOSE' ,
    'PARKING' ,
    'PARTNER' ,
    'PROFILE' ,
    'RICE' ,
    'ROUTINE' ,
    'SCHEDULE' ,
    'SWIMMING' ,
    'TELEPHONE' ,
    'TIP' ,
    'WINTER' ,
    'AIRLINE' ,
    'BAG' ,
    'BATTLE' ,
    'BED' ,
    'BILL' ,
    'BOTHER' ,
    'CAKE' ,
    'CODE' ,
    'CURVE' ,
    'DESIGNER' ,
    'DIMENSION' ,
    'DRESS' ,
    'EASE' ,
    'EMERGENCY' ,
    'EVENING' ,
    'EXTENSION' ,
    'FARM' ,
    'FIGHT' ,
    'GAP' ,
    'GRADE' ,
    'HOLIDAY' ,
    'HORROR' ,
    'HORSE' ,
    'HOST' ,
    'HUSBAND' ,
    'LOAN' ,
    'MISTAKE' ,
    'MOUNTAIN' ,
    'NAIL' ,
    'NOISE' ,
    'OCCASION' ,
    'PACKAGE' ,
    'PATIENT' ,
    'PAUSE' ,
    'PHRASE' ,
    'PROOF' ,
    'RACE' ,
    'RELIEF' ,
    'SAND' ,
    'SENTENCE' ,
    'SHOULDER' ,
    'SMOKE' ,
    'STOMACH' ,
    'STRING' ,
    'TOURIST' ,
    'TOWEL' ,
    'VACATION' ,
    'WEST' ,
    'WHEEL' ,
    'WINE' ,
    'ARM' ,
    'ASIDE' ,
    'ASSOCIATE' ,
    'BET' ,
    'BLOW' ,
    'BORDER' ,
    'BRANCH' ,
    'BREAST' ,
    'BROTHER' ,
    'BUDDY' ,
    'BUNCH' ,
    'CHIP' ,
    'COACH' ,
    'CROSS' ,
    'DOCUMENT' ,
    'DRAFT' ,
    'DUST' ,
    'EXPERT' ,
    'FLOOR' ,
    'GOD' ,
    'GOLF' ,
    'HABIT' ,
    'IRON' ,
    'JUDGE' ,
    'KNIFE' ,
    'LANDSCAPE' ,
    'LEAGUE' ,
    'MAIL' ,
    'MESS' ,
    'NATIVE' ,
    'OPENING' ,
    'PARENT' ,
    'PATTERN' ,
    'PIN' ,
    'POOL' ,
    'POUND' ,
    'REQUEST' ,
    'SALARY' ,
    'SHAME' ,
    'SHELTER' ,
    'SHOE' ,
    'SILVER' ,
    'TACKLE' ,
    'TANK' ,
    'TRUST' ,
    'ASSIST' ,
    'BAKE' ,
    'BAR' ,
    'BELL' ,
    'BIKE' ,
    'BLAME' ,
    'BOY' ,
    'BRICK' ,
    'CHAIR' ,
    'CLOSET' ,
    'CLUE' ,
    'COLLAR' ,
    'COMMENT'
]
secret_word = random.choice(words)  # chooses a random word from words
guessed_letter = []   # the letter which user enters , we compare this with the word

# -----------------------------------------------------------------------------------

def won_or_lost_message(message):
    window.fill((0, 0, 0))
    text = font2.render(message, 1, (255, 255, 255))
    window.blit(text, (WIDTH / 2 - text.get_width() / 2, HEIGHT / 2 - text.get_height() / 2))
    pygame.display.update()
    pygame.time.delay(1000)

# -----------------------------------------------------------------------------------

def draw():
    window.fill((31, 36, 37))
    # draw a big title
    text = font3.render('HANGMAN', 1, (255, 255, 255)) # title
    window.blit(text , (WIDTH / 2 - text.get_width() / 2 , 10))  #copying the text surface object to the display surface object at the center coordinate

    # Draw secret_word
    display_word = " "          # this is like a counter
    for letter in secret_word:
        if letter in guessed_letter:
            display_word += letter + " "    # once we guess the word  , and if the guessed letter is correct , then we no longer need the '_' so this removes the underscore and adds the letter we entered
        else:
            display_word += "_ "   # initially all the letters are underscored
    text = font2.render(display_word, 1, (0, 0, 0))  # render: create a text surface object on which text is drawn on it
    window.blit(text, (400, 200))  # copying the text surface object to the display surface object at the center coordinate

    # draw buttons - ALPHABETS with CIRCLES
    for letter in letters:
        x1, y1, ltr, visible = letter  # x and y axis for letters placement and ltr which has to be entered
        if visible:
            pygame.draw.circle(window , (255, 255, 255), (x1 , y1), radius, 3)  # 3 is the thickness
            text = font1.render(ltr , 1 , (255 , 255 , 255))  # Surface draw text on a new Surface
            window.blit(text , (x1 - text.get_width() / 2,y1 - text.get_height() / 2))  # this is done to align the letters in position inside the circles
            #  get_width/height tells how wide or big the text by rendering is
    window.blit(images[hangman_initial_status], (150, 100)) # this is going to add on top of fill the images
    pygame.display.update()


# -----------------------------------------------------------------------------------

def main_loop():
    global hangman_initial_status
    global fps
    # game loop
    run = True
    while run:
        clock.tick(fps)
        for event in pygame.event.get():  # whatever event is done it is getting is stored inside this place
            if event.type == pygame.QUIT:  # if type of event we're doing is clicking 'X' then
                run = False  # the program no more runs
            if event.type == pygame.MOUSEBUTTONDOWN:
                mouse_x , mouse_y = pygame.mouse.get_pos()  # tells the position of cursor
                # we have to see that whenever we click on circle that particular thing is selected

                for letter in letters:
                    x , y , ltr , visible = letter
                    # now we have to find the distance of position of mouse and position of letter
                    # it doesnt matter if its x1 - mouse_x or x1
                    if visible:
                        distance = math.sqrt((x - mouse_x) ** 2 + (y - mouse_y) ** 2)  # pythagoras theorem
                        if distance < radius:
                            letter[3] = False
                            guessed_letter.append((ltr))  # add the guessed letter to letter
                            if ltr not in secret_word:  # if guessed letter is not in the secret_word
                                hangman_initial_status += 1  # the draw the next hangman figure
        draw()
        won = True
        for letter in secret_word:  # to check for every letter in the secret_word (hidden one)
            if letter not in guessed_letter:
                won = False
        if won:
            won_or_lost_message('hehe you nailed it')
            print('the secret word was: ', secret_word)
            break

        if hangman_initial_status == 6:  # once all the images are finished and man hangs
            won_or_lost_message('Sorry, you lost Better luck next time')
            print('The secret_word was:', secret_word)
            break
        
        
# -----------------------------------------------------------------------------------

main_loop()
won_or_lost_message(secret_word)
pygame.quit()

# -----------------------------------------------------------------------------------
